name: Build and deploy after development change
push:
  branches:
    - main
jobs:
  build_dev_changes_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GNOSIS_WEBAPP }}"
          channelId: live
          projectId: gnosis-webapp
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
