# This is a basic workflow that is manually triggered

name: Manual workflow
on:
  repository_dispatch:
    types: [start-example2]
jobs:
  user_action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with: 
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GNOSIS_WEBAPP }}"
          projectId: gnosis-webapp
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
